// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 10);
user_pref("app.normandy.user_id", "cbc52c0b-a26e-446f-901b-2acee8f5d214");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1595957036);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1595956436);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1595956796);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1595956676);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1595956556);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1595956916);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1595956467);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1595957156);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 532480);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1595956406);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 96);
user_pref("browser.newtabpage.activity-stream.impressionId", "{e0045a3d-889b-4f44-b70b-eb9071799947}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1595956432116");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1595958207116");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1595956419656");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1595960019656");
user_pref("browser.sessionstore.resume_session_once", true);
user_pref("browser.shell.mostRecentDateSetAsDefault", "1595956416");
user_pref("browser.slowStartup.averageTime", 4432);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage_override.buildID", "20200708170202");
user_pref("browser.startup.homepage_override.mstone", "78.0.2");
user_pref("browser.startup.lastColdStartupCheck", 1595956409);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.placeholderName.private", "Google");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1595956415806");
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "78.0.2");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("dom.push.userAgentID", "62326eaa2aaf496abe36320deb4cbd7b");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 32);
user_pref("extensions.getAddons.cache.lastUpdate", 1595957038);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppVersion", "78.0.2");
user_pref("extensions.lastPlatformVersion", "78.0.2");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.doh-rollout@mozilla.org", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"5b2a94fb-844e-429b-8c15-93bed090a44d\",\"formautofill@mozilla.org\":\"2dd479b6-ba45-4aaf-b42d-5befd29502e0\",\"screenshots@mozilla.org\":\"eb91a2ac-5d9a-42b1-bc7e-d2789f7d20eb\",\"webcompat-reporter@mozilla.org\":\"17b0bfce-6ab8-480a-a41a-bdec9406bb98\",\"webcompat@mozilla.org\":\"fb0ecc04-34e4-400d-aba0-0e1b1078f3dd\",\"default-theme@mozilla.org\":\"5bd936f8-6eb7-4e42-a398-0ec0a317816d\",\"google@search.mozilla.org\":\"eb068f8b-1764-4cd0-b33c-d623261f752b\",\"amazondotcom@search.mozilla.org\":\"b29d9865-2021-4343-b39f-cc0bcd902a58\",\"bing@search.mozilla.org\":\"4ba39ea2-6538-4fc7-be2e-145dfab0557c\",\"ddg@search.mozilla.org\":\"9842d3b3-099c-4710-81eb-bd26e653c8b5\",\"ebay@search.mozilla.org\":\"a47f0c9a-294f-4b8e-b45a-26c7b4513eba\",\"wikipedia@search.mozilla.org\":\"3d71d6f9-b11e-4a84-9161-3b7ec5041745\"}");
user_pref("gfx.blacklist.layers.opengl", 4);
user_pref("gfx.blacklist.layers.opengl.failureid", "FEATURE_FAILURE_SOFTWARE_GL");
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1595956655);
user_pref("media.gmp-gmpopenh264.version", "1.8.1.1");
user_pref("media.gmp-manager.buildID", "20200708170202");
user_pref("media.gmp-manager.lastCheck", 1595956655);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.remote_settings.crlite_filters.checked", 1595956655);
user_pref("security.remote_settings.intermediates.checked", 1595956655);
user_pref("security.sandbox.content.tempDirSuffix", "1c245c63-3a06-4687-bfe1-e8194052988e");
user_pref("security.sandbox.plugin.tempDirSuffix", "13f53a25-fdec-4b17-9a39-a6c4845ac6e4");
user_pref("services.blocklist.addons.checked", 1595956655);
user_pref("services.blocklist.gfx.checked", 1595956655);
user_pref("services.blocklist.pinning.checked", 1595956655);
user_pref("services.blocklist.plugins.checked", 1595956655);
user_pref("services.settings.clock_skew_seconds", -249);
user_pref("services.settings.last_etag", "\"1595956649786\"");
user_pref("services.settings.last_update_seconds", 1595957165);
user_pref("services.settings.main.anti-tracking-url-decoration.last_check", 1595956655);
user_pref("services.settings.main.cfr-fxa.last_check", 1595956655);
user_pref("services.settings.main.cfr.last_check", 1595956655);
user_pref("services.settings.main.fxmonitor-breaches.last_check", 1595956718);
user_pref("services.settings.main.hijack-blocklists.last_check", 1595956655);
user_pref("services.settings.main.language-dictionaries.last_check", 1595956655);
user_pref("services.settings.main.messaging-experiments.last_check", 1595956655);
user_pref("services.settings.main.normandy-recipes-capabilities.last_check", 1595956655);
user_pref("services.settings.main.public-suffix-list.last_check", 1595956655);
user_pref("services.settings.main.search-config.last_check", 1595956655);
user_pref("services.settings.main.search-default-override-allowlist.last_check", 1595956655);
user_pref("services.settings.main.sites-classification.last_check", 1595956655);
user_pref("services.settings.main.url-classifier-skip-urls.last_check", 1595956655);
user_pref("services.settings.main.whats-new-panel.last_check", 1595956655);
user_pref("services.settings.security.onecrl.checked", 1595956655);
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1595956404);
user_pref("toolkit.telemetry.cachedClientID", "6717608c-e67f-4b57-9dd3-83439c37ef92");
user_pref("toolkit.telemetry.previousBuildID", "20200708170202");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
