// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 10);
user_pref("app.normandy.user_id", "888332a8-f3f9-4965-b977-e0adcfd14fe6");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1597295995);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1597295395);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1597295515);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1597295755);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1597295635);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1597295875);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1597296235);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1597296115);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.amount_written", 7420);
user_pref("browser.cache.disk.capacity", 491520);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1596514392);
user_pref("browser.laterrun.bookkeeping.sessionCount", 5);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 96);
user_pref("browser.newtabpage.activity-stream.impressionId", "{61d2ed9d-1bd4-4b96-9ca6-b38d090a1d07}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1597297196232");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1597299005232");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1597295381745");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1597298981745");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20200708170202");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1597295372");
user_pref("browser.slowStartup.averageTime", 0);
user_pref("browser.slowStartup.samples", 0);
user_pref("browser.startup.homepage_override.buildID", "20200708170202");
user_pref("browser.startup.homepage_override.mstone", "78.0.2");
user_pref("browser.startup.homepage_override.once", "{\"message_id\":\"WNP_MOMENTS_1\",\"url\":\"https://www.mozilla.org/firefox/welcome/1/\",\"expire\":1597900173337}");
user_pref("browser.startup.lastColdStartupCheck", 1597295368);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"toolbar-menubar\",\"TabsToolbar\",\"PersonalToolbar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.placeholderName.private", "Google");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1596514406212");
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "78.0.2");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("dom.push.userAgentID", "62984c7d6b6d4b0f8d9abf5b991c6743");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 32);
user_pref("extensions.getAddons.cache.lastUpdate", 1597295997);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20200708170202");
user_pref("extensions.lastAppVersion", "78.0.2");
user_pref("extensions.lastPlatformVersion", "78.0.2");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.doh-rollout@mozilla.org", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"ff3e4587-4e7b-4d63-89ec-5871a1937942\",\"formautofill@mozilla.org\":\"91abd3f3-5bee-41fd-a3b6-afb0d9273a1c\",\"screenshots@mozilla.org\":\"0c08486a-9da9-40ae-b550-b915e4b3eb29\",\"webcompat-reporter@mozilla.org\":\"d5801d7a-8b95-42ea-b712-768b4563c51d\",\"webcompat@mozilla.org\":\"a2bd6fc7-c9bd-4aa8-8a2a-1d478f163b49\",\"default-theme@mozilla.org\":\"198c1a9d-1e8a-47e2-b41a-6d64c2605016\",\"google@search.mozilla.org\":\"3823131a-ec41-4d44-8e68-a2d626677847\",\"amazondotcom@search.mozilla.org\":\"c62f2d46-3e5b-4851-85cb-b4bd1c17eb85\",\"bing@search.mozilla.org\":\"e9971370-72e4-4c1e-acb5-c02552874944\",\"ddg@search.mozilla.org\":\"4be01a01-2c0d-42ce-9d53-62a516c2e9eb\",\"ebay@search.mozilla.org\":\"f0b74ba5-8f71-46fe-8c0a-05b168523dcd\",\"wikipedia@search.mozilla.org\":\"8a420f53-174f-4631-a6eb-8fee8f0e5d36\"}");
user_pref("gfx.blacklist.layers.opengl", 4);
user_pref("gfx.blacklist.layers.opengl.failureid", "FEATURE_FAILURE_SOFTWARE_GL");
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1596517591);
user_pref("media.gmp-gmpopenh264.version", "1.8.1.1");
user_pref("media.gmp-manager.buildID", "20200708170202");
user_pref("media.gmp-manager.lastCheck", 1597295488);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.remote_settings.crlite_filters.checked", 1597295875);
user_pref("security.remote_settings.intermediates.checked", 1597295875);
user_pref("security.sandbox.content.tempDirSuffix", "b34b2553-ae63-457b-b8cd-8cfafaf04afc");
user_pref("security.sandbox.plugin.tempDirSuffix", "8bb88885-ca90-4088-88b1-9a6c9fa6ba4c");
user_pref("services.blocklist.addons.checked", 1597295875);
user_pref("services.blocklist.gfx.checked", 1597295875);
user_pref("services.blocklist.pinning.checked", 1597295875);
user_pref("services.blocklist.plugins.checked", 1597295875);
user_pref("services.settings.clock_skew_seconds", 0);
user_pref("services.settings.last_etag", "\"1597280277565\"");
user_pref("services.settings.last_update_seconds", 1597295875);
user_pref("services.settings.main.anti-tracking-url-decoration.last_check", 1597295875);
user_pref("services.settings.main.cfr-fxa.last_check", 1597295875);
user_pref("services.settings.main.cfr.last_check", 1597295875);
user_pref("services.settings.main.fxmonitor-breaches.last_check", 1597295875);
user_pref("services.settings.main.hijack-blocklists.last_check", 1597295875);
user_pref("services.settings.main.language-dictionaries.last_check", 1597295875);
user_pref("services.settings.main.messaging-experiments.last_check", 1597295875);
user_pref("services.settings.main.normandy-recipes-capabilities.last_check", 1597295875);
user_pref("services.settings.main.public-suffix-list.last_check", 1597295875);
user_pref("services.settings.main.search-config.last_check", 1597295875);
user_pref("services.settings.main.search-default-override-allowlist.last_check", 1597295875);
user_pref("services.settings.main.sites-classification.last_check", 1597295875);
user_pref("services.settings.main.url-classifier-skip-urls.last_check", 1597295875);
user_pref("services.settings.main.whats-new-panel.last_check", 1597295875);
user_pref("services.settings.security.onecrl.checked", 1597295875);
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1597295361);
user_pref("toolkit.telemetry.cachedClientID", "4b25efb7-a57a-4f4e-b3ed-258c03bb686e");
user_pref("toolkit.telemetry.previousBuildID", "20200708170202");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
