// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 10);
user_pref("app.normandy.user_id", "29936e5f-238a-47a6-b8ac-f8b5a8ba6332");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1596083053);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1596086110);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1596082498);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1596087737);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1596082813);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1596082933);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1596082539);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1596083174);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.amount_written", 6606);
user_pref("browser.cache.disk.capacity", 512000);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.download.panel.shown", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1596082479);
user_pref("browser.laterrun.bookkeeping.sessionCount", 4);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 96);
user_pref("browser.newtabpage.activity-stream.impressionId", "{62dd57ce-4f6d-4fe6-b494-f2828bcab67b}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1596087743295");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1596089523295");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1596086095902");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1596089695902");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20200708170202");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1596087737");
user_pref("browser.slowStartup.averageTime", 3857);
user_pref("browser.slowStartup.samples", 4);
user_pref("browser.startup.homepage_override.buildID", "20200708170202");
user_pref("browser.startup.homepage_override.mstone", "78.0.2");
user_pref("browser.startup.lastColdStartupCheck", 1596087735);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"toolbar-menubar\",\"TabsToolbar\",\"PersonalToolbar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.placeholderName.private", "Google");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1596082794879");
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "78.0.2");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("dom.push.userAgentID", "cc289b74e76f4c9f891437ba66ab1622");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 32);
user_pref("extensions.getAddons.cache.lastUpdate", 1596083055);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20200708170202");
user_pref("extensions.lastAppVersion", "78.0.2");
user_pref("extensions.lastPlatformVersion", "78.0.2");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.doh-rollout@mozilla.org", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"238cd76f-c40c-4fdd-a138-7a535cf9bf47\",\"formautofill@mozilla.org\":\"964b0b75-c1e7-42d9-9cf6-8c3db6e13c85\",\"screenshots@mozilla.org\":\"568d35ed-03c8-4d39-868d-b040f5a2dd75\",\"webcompat-reporter@mozilla.org\":\"a30bb7b2-9d8d-42f2-a4d1-ba8f25a10d2c\",\"webcompat@mozilla.org\":\"b5fdb89c-0048-45ab-9b79-a8dfedc25307\",\"default-theme@mozilla.org\":\"4d4dfcd1-5add-449d-9215-7c588236a3c1\",\"google@search.mozilla.org\":\"2a176159-a123-46a0-8e22-ebe11b30a914\",\"amazondotcom@search.mozilla.org\":\"fef62aa7-4f41-4c87-999d-6af41c9338b0\",\"bing@search.mozilla.org\":\"7f616035-07d9-4a4c-a27f-30408c71afa3\",\"ddg@search.mozilla.org\":\"47008bf5-382d-4757-81e9-be024ad531dd\",\"ebay@search.mozilla.org\":\"c0d5e050-c849-4b41-9f7d-4ec0f329c227\",\"wikipedia@search.mozilla.org\":\"bf0b5d06-121d-4766-905d-944ca9dc14b0\"}");
user_pref("gfx.blacklist.layers.opengl", 4);
user_pref("gfx.blacklist.layers.opengl.failureid", "FEATURE_FAILURE_SOFTWARE_GL");
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1596082917);
user_pref("media.gmp-gmpopenh264.version", "1.8.1.1");
user_pref("media.gmp-manager.buildID", "20200708170202");
user_pref("media.gmp-manager.lastCheck", 1596082916);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.remote_settings.crlite_filters.checked", 1596082916);
user_pref("security.remote_settings.intermediates.checked", 1596082916);
user_pref("security.sandbox.content.tempDirSuffix", "dd901b3b-fc4e-47d6-b97e-9ca99df2aa2d");
user_pref("security.sandbox.plugin.tempDirSuffix", "959ed950-79fa-4403-b9dd-e7bf8be35b43");
user_pref("services.blocklist.addons.checked", 1596082916);
user_pref("services.blocklist.gfx.checked", 1596082916);
user_pref("services.blocklist.pinning.checked", 1596082916);
user_pref("services.blocklist.plugins.checked", 1596082916);
user_pref("services.settings.clock_skew_seconds", -1240);
user_pref("services.settings.last_etag", "\"1596067279709\"");
user_pref("services.settings.last_update_seconds", 1596084173);
user_pref("services.settings.main.anti-tracking-url-decoration.last_check", 1596082916);
user_pref("services.settings.main.cfr-fxa.last_check", 1596082916);
user_pref("services.settings.main.cfr.last_check", 1596082916);
user_pref("services.settings.main.fxmonitor-breaches.last_check", 1596082916);
user_pref("services.settings.main.hijack-blocklists.last_check", 1596082916);
user_pref("services.settings.main.language-dictionaries.last_check", 1596082916);
user_pref("services.settings.main.messaging-experiments.last_check", 1596082916);
user_pref("services.settings.main.normandy-recipes-capabilities.last_check", 1596082916);
user_pref("services.settings.main.public-suffix-list.last_check", 1596082916);
user_pref("services.settings.main.search-config.last_check", 1596082916);
user_pref("services.settings.main.search-default-override-allowlist.last_check", 1596082916);
user_pref("services.settings.main.sites-classification.last_check", 1596082916);
user_pref("services.settings.main.url-classifier-skip-urls.last_check", 1596082916);
user_pref("services.settings.main.whats-new-panel.last_check", 1596082916);
user_pref("services.settings.security.onecrl.checked", 1596082916);
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1596087733);
user_pref("toolkit.telemetry.cachedClientID", "7c7bb12c-d706-4101-8e9d-7e5db5b1e802");
user_pref("toolkit.telemetry.previousBuildID", "20200708170202");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
